<?php

namespace PHPOrchestra\DisplayBundle;

use PHPOrchestra\DisplayBundle\DependencyInjection\Compiler\DisplayBlockCompilerPass;
use PHPOrchestra\DisplayBundle\DependencyInjection\Compiler\DisplayFieldCompilerPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class PHPOrchestraDisplayBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub

        $container->addCompilerPass(new DisplayBlockCompilerPass());
    }
}
